Enable support for Pycharm using the built-in web server
lmichelin/open-github-links-in-ide pull request #16
Opened 2021-02-08 19:26 UTC by rnw159

Pycharm has a built-in webserver that makes it easy to open files. I have been using this locally for a while and decided to make a pr to share my work.

Cheers!

There might be better ways to do this, but this works really well for me.

2021-03-06 23:02 UTC, lmichelin commented on src/popup.html
> +      <option value="pycharm">Pycharm (Built-in web server)</option>
```suggestion
      <option value="pycharm">PyCharm (built-in web server)</option>
```

2021-03-06 23:07 UTC, lmichelin requested changes

2021-03-06 23:07 UTC, lmichelin commented on src/inject.ts
> +        Http.send();
fetch(url)

2021-03-06 23:08 UTC, lmichelin commented on README.md
> +- Pycharm (Built-in web server)
```suggestion
- PyCharm (built-in web server)
```

2021-03-06 23:11 UTC, lmichelin commented on src/inject.ts
> +        const url = `http://localhost:63342/api/file?file=${OPTIONS.localPathForRepositories}/${repo}/${file}&line=${line ? `${line}` : "1"}`
```suggestion
        const url = `http://localhost:63342/api/file?file=${OPTIONS.localPathForRepositories}/${repo}/${file}&line=${line ?? "1"}`
```

2021-03-06 23:13 UTC, lmichelin commented on README.md
> +If you wish to use Pycharm (Built-in web server) then you must enable the intellij built-in web server (see [here](https://www.jetbrains.com/help/idea/php-built-in-web-server.html#configuring-built-i
```suggestion
If you wish to use PyCharm (Built-in web server) then you must enable the intellij built-in web server (see [here](https://www.jetbrains.com/help/idea/php-built-in-web-server.html#configuring-built-in-web-server)) on port 63342.
```

Btw I think that this line can go after line 25 ;)

2021-03-07 00:26 UTC, merged

2021-03-07 00:53 UTC, lmichelin commented
Thanks @rnw159 for your contribution :wink: 

I made some updates to your PR in commit 868fc5d:
- replace "PyCharm" with "JetBrains" as the build-in web server is available in many JetBrains editors
- add a JetBrains icon
- use `fetch` instead of `XMLHttpRequest`
- show an alert if the API call fails
- refactor some code

I just published v1.1.7 to Chrome Web Store and Firefox Addons.

2021-03-08 19:16 UTC, rnw159 commented
Hey thanks for merging! I love this extension 💚